productms.console.enabled: true
productms.console.path: /h2
productms.datasource.url: jdbc:h2:mem:greetDb;DB_CLOSE_DELAY=-1
productms.datasource.username: sa
productms.datasource.password:
productms.datasource.driver: org.h2.Driver


productms.eureka.url: http://192.168.99.100:8761/eureka
message: From dev profile under product microservice    